"""Internal V token and external USDC currency.

These are intentionally separate types: the type checker prevents
accidental ``V + USDC`` while keeping arithmetic between same-currency
values ergonomic. Both are quantised to six decimal places — the standard
USDC precision — to avoid floating-point drift over thousands of ticks.

V can go negative (a member's balance during an open credit position).
USDC cannot — the Liquidity Fund is bounded below by zero by design.
"""

from __future__ import annotations

from decimal import ROUND_HALF_EVEN, Decimal
from typing import TYPE_CHECKING, Self

from pydantic import RootModel, field_validator

_QUANTUM = Decimal("0.000001")

# Construction-time accepted types. Coerced in field validators.
_Numeric = Decimal | int | str | float


def _quantize(value: Decimal) -> Decimal:
    return value.quantize(_QUANTUM, rounding=ROUND_HALF_EVEN)


class V(RootModel[Decimal]):
    """Internal Club token.

    Quantised to 6 decimal places. Can be negative (credit positions).
    """

    model_config = {"frozen": True}

    if TYPE_CHECKING:
        # The runtime ``__init__`` is generated by pydantic and accepts any
        # value the field validator can coerce. This stub mirrors that for
        # mypy without altering runtime behavior.
        def __init__(self, root: _Numeric | V = ..., /) -> None: ...

    @field_validator("root", mode="before")
    @classmethod
    def _coerce(cls, value: object) -> Decimal:
        if isinstance(value, Decimal):
            return _quantize(value)
        if isinstance(value, V):
            return value.root
        return _quantize(Decimal(str(value)))

    @classmethod
    def zero(cls) -> Self:
        return cls(Decimal(0))

    # ----- arithmetic ------------------------------------------------------

    def __add__(self, other: V) -> V:
        if not isinstance(other, V):
            return NotImplemented
        return V(self.root + other.root)

    def __sub__(self, other: V) -> V:
        if not isinstance(other, V):
            return NotImplemented
        return V(self.root - other.root)

    def __neg__(self) -> V:
        return V(-self.root)

    def __mul__(self, factor: Decimal | int) -> V:
        if isinstance(factor, V | USDC):
            return NotImplemented
        return V(self.root * Decimal(str(factor)))

    __rmul__ = __mul__

    # ----- ordering --------------------------------------------------------

    def __lt__(self, other: V) -> bool:
        if not isinstance(other, V):
            return NotImplemented
        return self.root < other.root

    def __le__(self, other: V) -> bool:
        if not isinstance(other, V):
            return NotImplemented
        return self.root <= other.root

    def __gt__(self, other: V) -> bool:
        if not isinstance(other, V):
            return NotImplemented
        return self.root > other.root

    def __ge__(self, other: V) -> bool:
        if not isinstance(other, V):
            return NotImplemented
        return self.root >= other.root

    # ----- predicates ------------------------------------------------------

    def is_zero(self) -> bool:
        return self.root == 0

    def is_positive(self) -> bool:
        return self.root > 0

    def is_negative(self) -> bool:
        return self.root < 0

    def __str__(self) -> str:
        return f"V({self.root})"


class USDC(RootModel[Decimal]):
    """External stablecoin. Always non-negative."""

    model_config = {"frozen": True}

    if TYPE_CHECKING:

        def __init__(self, root: _Numeric | USDC = ..., /) -> None: ...

    @field_validator("root", mode="before")
    @classmethod
    def _coerce(cls, value: object) -> Decimal:
        if isinstance(value, Decimal):
            decimal_value = value
        elif isinstance(value, USDC):
            return value.root
        else:
            decimal_value = Decimal(str(value))
        if decimal_value < 0:
            raise ValueError(f"USDC must be non-negative, got {decimal_value}")
        return _quantize(decimal_value)

    @classmethod
    def zero(cls) -> Self:
        return cls(Decimal(0))

    def __add__(self, other: USDC) -> USDC:
        if not isinstance(other, USDC):
            return NotImplemented
        return USDC(self.root + other.root)

    def __sub__(self, other: USDC) -> USDC:
        """Subtract another USDC amount.

        Raises ValueError if the result would be negative — USDC is
        non-negative by construction.
        """
        if not isinstance(other, USDC):
            return NotImplemented
        return USDC(self.root - other.root)

    def __mul__(self, factor: Decimal | int) -> USDC:
        if isinstance(factor, V | USDC):
            return NotImplemented
        return USDC(self.root * Decimal(str(factor)))

    __rmul__ = __mul__

    def __lt__(self, other: USDC) -> bool:
        if not isinstance(other, USDC):
            return NotImplemented
        return self.root < other.root

    def __le__(self, other: USDC) -> bool:
        if not isinstance(other, USDC):
            return NotImplemented
        return self.root <= other.root

    def __gt__(self, other: USDC) -> bool:
        if not isinstance(other, USDC):
            return NotImplemented
        return self.root > other.root

    def __ge__(self, other: USDC) -> bool:
        if not isinstance(other, USDC):
            return NotImplemented
        return self.root >= other.root

    def is_zero(self) -> bool:
        return self.root == 0

    def is_positive(self) -> bool:
        return self.root > 0

    def __str__(self) -> str:
        return f"USDC({self.root})"
